### ISSUE TITLE
Config variable ${APACHE_SERVERNAME} is not defined

### ISSUE THREAD

**Issue by event15** [einfallstoll/docker-phppgadmin#2]
My docker-compose configuration:

``` yaml
version: "2"

services:
  database:
    image: powercontent/pc-database-server:latest
    build: ./services/database
    container_name: pc-database-server
    hostname: pc-database-server
    restart: always

    volumes:
      - data:/data
    working_dir: /data
    env_file:
          - services/database/postgres.dev.env
    networks:
      - pc
    ports:
      - "5432:5432"

  pgadmin:
    image: einfallstoll/phppgadmin
    restart: always
    hostname: pc-database-admin
    container_name: pc-database-admin
    env_file:
      - services/database/phppgadmin.dev.env
    links:
      - "database:pgadmin"
    ports:
      - "80:80"
    networks:
      - pc
volumes:
  data:
    driver: local
networks:
  pc:
    external: true
```

My phppgadmin.dev.env:

```
APACHE_SERVERNAME=localhost
POSTGRES_HOST=pc-database-server
POSTGRES_PORT=5432

#POSTGRES_DEFAULTDB=defaultdb
#APACHE_SERVERADMIN=admin@localhost
#APACHE_DOCUMENTROOT=/var/www
#APACHE_RUN_USER=www-data
#APACHE_RUN_GROUP=www-data
#APACHE_LOG_DIR=/var/web/log/apache2
#APACHE_PID_FILE=/var/run/apache2.pid
#APACHE_RUN_DIR=/var/run/apache2
#APACHE_LOCK_DIR=/var/lock/apache2
```

Docker containers after build:
$ docker ps

```
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS              PORTS                         NAMES
af857a054e54        einfallstoll/phppgadmin                  "bash start.sh"          10 minutes ago      Up 10 minutes       0.0.0.0:80->80/tcp, 443/tcp   pc-database-admin
94906f71e79a        powercontent/pc-database-server:latest   "/docker-entrypoint.s"   10 minutes ago      Up 10 minutes       0.0.0.0:5432->5432/tcp        pc-database-server
```

Docker compose services:

```
$ docker-compose ps
       Name                     Command               State              Ports
-----------------------------------------------------------------------------------------
pc-database-admin    bash start.sh                    Up      443/tcp, 0.0.0.0:80->80/tcp
pc-database-server   /docker-entrypoint.sh postgres   Up      0.0.0.0:5432->5432/tcp
```

Docker network inspect:

```
$ docker network inspect pc
[
    {
        "Name": "pc",
        "Id": "f85e4dc8189f97da309e376f48b557c27fb7b9a1040cca85760ec9214474561d",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "172.18.0.0/16",
                    "Gateway": "172.18.0.1/16"
                }
            ]
        },
        "Internal": false,
        "Containers": {
            "94906f71e79a97540d500cfe5d92790145f18678a9cb39774524b7724320a728": {
                "Name": "pc-database-server",
                "EndpointID": "af7bc584da9138cee53a2996b4e58992f78594b8a4469e2214fb2344c703c2bd",
                "MacAddress": "02:42:ac:12:00:02",
                "IPv4Address": "172.18.0.2/16",
                "IPv6Address": ""
            },
            "af857a054e54a32efd54b3bc5c9c3271d59418c6a14eab2cd3e0f00310330c6a": {
                "Name": "pc-database-admin",
                "EndpointID": "5646f22f143948ec7504fc50a7b8aa87209171820afe99d9c79c93a6c627b99c",
                "MacAddress": "02:42:ac:12:00:03",
                "IPv4Address": "172.18.0.3/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]
```

I see that error when I try to build my services on Windows 8,1:

```
$ docker exec -it pc-database-admin service apache2 start
Starting web server: apache2[Thu Oct 13 19:44:53.535431 2016] [core:warn] [pid 49] AH00111: Config variable ${APACHE_SERVERNAME} is not defined
(98)Address already in use: AH00072: make_sock: could not bind to address [::]:80
(98)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down
AH00015: Unable to open logs
Action 'start' failed.
The Apache error log may have more information.
.
```

And this is logs for apache:

```
$ docker exec -it pc-database-admin cat /var/log/apache2/error.log
[Thu Oct 13 19:31:45.302136 2016] [mpm_prefork:notice] [pid 5] AH00163: Apache/2.4.10 (Debian) configured -- resuming normal operations
[Thu Oct 13 19:31:45.314819 2016] [core:notice] [pid 5] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
```

My docker:

```
$ docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 56
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 44
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.17-boot2docker
Operating System: Boot2Docker 1.12.1 (TCL 7.2); HEAD : ef7d0b4 - Thu Aug 18 21:18:06 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: default
ID: QI2C:VAST:DME7:UM6F:YIXC:XNCC:BRZN:U3C6:J5F6:ZYAV:52JH:6EIV
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 25
 Goroutines: 40
 System Time: 2016-10-13T19:46:38.962049848Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8
```

And docker-compose version:

```
$ docker-compose version
docker-compose version 1.8.0, build d988a55
docker-py version: 1.9.0
CPython version: 2.7.11
OpenSSL version: OpenSSL 1.0.2d 9 Jul 2015
```

But the same configuration in yml, versions of docker and docker-compose are running on Kubuntu.
